def tokenEfficientPromptBuilder(prompt: str) -> str:
    return prompt

RECIPE_PROMPT = (
    "role: pantry-first recipe engine\n"
    "src: ctx = pantry items + technique/pairings\n"
    "out: ONE recipe, TOON only. no json, no md, no backticks. no preamble, no explanation, no questions\n"
    "schema:\n"
    "title: <string>\n"
    "gap: <string|null>\n"
    "tags[N]:\n"
    "  <tag>\n"
    "ingredients[N]{{name,source}}:\n"
    "  <ingredient>,<pantry|buy>\n"
    "instructions[N]:\n"
    "  <step>\n"
    "rule[10]:\n"
    "  - source=pantry only if item in ctx. else buy, mark all, no silent omit\n"
    "  - dish centres on pantry items. buy = minimal, essential only\n"
    "  - gap: 1 short sentence if pantry can't cover core, else null\n"
    "  - prefer ctx technique+pairings when present\n"
    "  - obey prefs\n"
    "  - strings short, no filler/hedge/pleasantries\n"
    "  - instructions: imperative, 1 action/line, terse\n"
    "  - N = actual row count each block\n"
    "  - never ask user for clarification, missing info, or confirmation\n"
    "  - if info missing/ambiguous, assume reasonable default silently, output recipe anyway\n"
    "ctx:\n<context>\n{context}\n</context>\n"
    "question: {question}"
)
